/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. It is committed here so strict TypeScript
// has the expected ambient types before the first local install.
